### ISSUE TITLE
CoreOS is EOL

### ISSUE THREAD

**Issue by wuservices** [JetBrains/teamcity-google-template#20]
Just received a notification from Google that CoreOS is EOL and they won't be supporting it anymore.

https://coreos.com/os/eol/
On May 26, 2020, CoreOS Container Linux will reach its end of life and will no longer receive updates.

Will this stop to work after that? Either way, this should use something else as a base now.

**Comment by undimmable** [comment]
@wuservices, thank you for the reporting. We will research the possible solutions in the upcoming release. Please follow the issue in YouTrack for updates
https://youtrack.jetbrains.com/issue/TW-64973
