### ISSUE TITLE
Default root volume size is is inadequate for major upgrades

### ISSUE THREAD

**Issue by matevarga** [JetBrains/teamcity-google-template#5]
Deploying TC 2018.1.4 with this template sets up a 7 GB root volume. When upgrading to 2019.1, the new Docker image is 1.1 GBs, and during the extraction phase the process stops because of insufficient disk space.

Solution: root disk should be set to e.g. 10 GBs. Alternatively, Docker image storage should be moved to /mnt/data.

**Comment by undimmable** [comment]
Fixed by https://github.com/seansaleh/teamcity-google-template/commit/1f63f687fdaf71908e725c3f29c7ad4e1110acea

**Comment by seansaleh** [comment]
Note, @dimyriy that commit you reference is only on my fork :)
I've opened a PR so it can be in upstream

**Comment by undimmable** [comment]
@seansaleh, yup, my bad.
Fixed by https://github.com/JetBrains/teamcity-google-template/commit/ee70a1c1caa204731d35e7818f390612fb82cdde
