### ISSUE TITLE
Unable to upgrade TC deployment to version 2019.1

### ISSUE THREAD

**Issue by supermartzin** [JetBrains/teamcity-google-template#6]
Hi,

I'm trying to upgrade our TeamCity server deployed directly through this template on Google Cloud Platform from version 2018.2.4 to 2019.1

I'm following the instructions [here at the readme](https://github.com/JetBrains/teamcity-google-template#teamcity-update) but I'm keep getting the following error:
```
Manifest expansion encountered the following errors: Invalid properties for 'teamcity.jinja':
2019.1 is not of type 'string' at ['version']
Resource: teamcity-jinja Resource: config
```

I've tried to execute the update command with `version:"2019.1"` or `version:'2019.1'` but none of it worked.

Do you have any idea what could be causing this issue?

Many thanks in advance.

**Comment by burnasheva** [comment]
@supermartzin thank you for reporting it. Seems the problem with 2019.1 version. Could you please try to specify 2019.1.1 version instead? It's the latest bugfix release and with this version, the problem doesn't reproduce. 

Here is the link to the issue in our YouTrack - https://youtrack.jetbrains.com/issue/TW-60973.

**Comment by supermartzin** [comment]
@burnasheva Thanks! Indeed, specifying version 2019.1.1 allowed upgrading without problems.

But after the upgrade, I reset the cloud instance as it is said in instructions and TeamCity didn't start, even after waiting for a long time.
So I logged in to the VM instance where the server is running and looked up its service:

```
UNIT                      LOAD    ACTIVE      SUB       JOB      DESCRIPTION 
teamcity-server.service   loaded  activating  start-pre start    TeamCity Server 
```

It's still stuck in this state event after several restarts later.

Any idea how to proceed?

Thanks.

**Comment by burnasheva** [comment]
@supermartzin do you see any errors in teamcity-server.log (or any other server logs)?

**Comment by supermartzin** [comment]
@burnasheva Where exactly can I find it?

Besides that, I haven't found any error or even warning in other logs.

**Comment by burnasheva** [comment]
@supermartzin you can check `/mnt/data/teamcity-server/logs` or execute `sudo journalctl -u <serviceName>` command.

**Comment by supermartzin** [comment]
@burnasheva thanks! I checked the logs and found this little message repeated several times:

```
failed to register layer: Error processing tar file(exit status 1): write /opt/teamcity/webapps/ROOT/WEB-INF/plugins/idea-tool/bundled/idea.zip: no space left on device
```

So I added more space to the disk drive and voila, it all works now!

Thanks for your help :)
