### ISSUE TITLE
What are the specs for the custom machines? (CPU GHz, RAM Gb)?

### ISSUE THREAD

**Issue by eyeezzi** [JetBrains/teamcity-google-template#9]
https://github.com/JetBrains/teamcity-google-template/blob/c56c49f9934e69bbd590674c0a65cbc66f1e3049/virtual-machine.jinja#L39

**Comment by undimmable** [comment]
it's 4 CPUs and 8Gb RAM. See the [documentation of gcloud create command](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create):

> You can also specify custom machine types with the string "custom-CPUS-RAM" where CPUS is the number of virtual CPUs and RAM is the amount of RAM in MiB.
>
> For example, to create a node pool using custom machines with 2 vCPUs and 12 GB of RAM:
>
>  `$ gcloud container clusters create high-mem-pool \
      --machine-type=custom-2-12288`

The CPU frequency is not defined precisely, instead gcloud defines the CPU platform. In this case the default one is used. Which CPU platform is default depends on the actual region. Please refer to the [gcloud documentation](https://cloud.google.com/compute/docs/regions-zones/) for the details about CPU platforms.
